### ISSUE TITLE
Graphs not being saved to pngs

### ISSUE THREAD

**Issue by martmists** [mgedmin/objgraph#29]
Using the example from the docs:

```py
>>> x = []
>>> y = [x, [x], dict(x=x)]
>>> import objgraph
>>> objgraph.show_refs([y], filename="x.png")
Graph written to C:\Users\Userame\AppData\Local\Temp\objgraph-99xk348b.dot (4 nodes)
Image renderer (dot) not found, not doing anything else
```
Despite having graphviz and xdot installed.

**Comment by mgedmin** [comment]
Is `dot.exe` on your `%PATH%`?

**Comment by martmists** [comment]
It is.

**Comment by mgedmin** [comment]
The bug is probably in the [`_program_in_path()`](https://github.com/mgedmin/objgraph/blob/master/objgraph.py#L985) function.  You can verify that by trying to see whether `objgraph._program_in_path('dot')` returns False.

Can you tell me the value of `os.environ.get('PATH')`, and also the actual location of `dot.exe`?

**Comment by elfxiong** [comment]
I am getting the same error message. For me, `xdot` instead of `dot` is in the %PATH%.
Isn't it supposed to save to a image file even if xdot is not installed?

**Comment by mgedmin** [comment]
> Isn't it supposed to save to a image file even if xdot is not installed?

Yes, provided that `dot` is installed.

I'm still awaiting additional information (e.g. answers to my [earlier questions](https://github.com/mgedmin/objgraph/issues/29#issuecomment-263565010)) since I cannot reproduce this problem myself.

**Comment by elfxiong** [comment]
Oh, I just figured that `dot` is different from `xdot`, and is installed by Graphviz (not the Python package of the same name).

I don't have this problem any more after installing Graphviz and making sure `dot.exe` is in the %PATH%.

**Comment by luofengwei** [comment]
I mad the same mistake. When i use 'pip install graphviz', it has no dot.exe, only dot.py.

I don't have this problem any more after installing graphviz.mis  from "https://graphviz.gitlab.io/_pages/Download/Download_windows.html"
