### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [mgedmin/objgraph#76]
Is it possible next time on release new version make the github release to have entry on https://github.com/mgedmin/objgraph/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.
My automation process those notification trying make preliminary automated upgrade of building packages which allow save some time on maintaining packaging procedures.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release

**Comment by mgedmin** [comment]
I should be able to run `gh release create`  from my Makefile, and it's apparently interactive.  

I'd test it today, except objgraph unit tests fail on 3.13 and I don't want to release it in that state.

**Comment by mgedmin** [comment]
I've added the reminder to my `make release` and tested it out today, with a slight hiccup (3.6.1 was released in February, not today, but github doesn't let me backdate releases and shows it as "released 3 minutes ago").

**Comment by mgedmin** [comment]
Should I try to create GH releases for all the previous release tags?

**Comment by kloczek** [comment]
For the resting .. why not? 😄
